[functions.query-data]
enabled = true
verify_jwt = true
import_map = "./functions/query-data/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/query-data/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/query-data/*.html" ]

[functions.query-names]
enabled = true
verify_jwt = true
import_map = "./functions/query-names/deno.json"
entrypoint = "./functions/query-names/index.ts"

[functions.analyze-district-price]
enabled = true
verify_jwt = true
import_map = "./functions/analyze-district-price/deno.json"
entrypoint = "./functions/analyze-district-price/index.ts"

[functions.analyze-project-ranking]
enabled = true
verify_jwt = true
import_map = "./functions/analyze-project-ranking/deno.json"
entrypoint = "./functions/analyze-project-ranking/index.ts"

[functions.public-report]
verify_jwt = false

[functions.analyze-data]
enabled = true
verify_jwt = true
import_map = "./functions/analyze-data/deno.json"
entrypoint = "./functions/analyze-data/index.ts"

[auth]
site_url = "https://sqm7.github.io/kthd"